### ISSUE TITLE
Implement latest version of AuthZEN basic permit-deny API

### ISSUE THREAD

**Issue by ggebel** [hexa-org/policy-opa#40]
https://openid.github.io/authzen/

**Comment by independentid** [comment]
The 1-1 preview spec: https://github.com/openid/authzen/blob/main/api/authorization-api-1_1.md

Also see: https://oidf.slack.com/archives/C0630873JGK/p1726883725029839

**Comment by independentid** [comment]
Implemented in 0.68.0
